version: "3"

services:

  cassandra1:
    image: cassandra:3.9
    container_name: cassandra
    environment:
      - "CASSANDRA_CLUSTER_NAME=WhyCassandraCluster"
    ports:
      - "9042:9042"
    volumes:
      - "cv1:/var/lib/cassandra"
      - "./cassandra/:/etc/cassandra/"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  cv1:
    driver: local
